### PR TITLE
Allow floating-point values for `crosshairsize`

### PR DESCRIPTION
**Pull request by Calinou**
This makes finer size adjustments possible.

### CODE REVIEW

**Review by SalatielSauer — COMMENTED** [review]
just a note, the [guislider](https://github.com/tomatenquark/code/blob/94cc3d7325e3f463a453710be23ee0a3be5dfb57/src/engine/menus.cpp#L388) command does not handle float variables very well, making it impossible to change the crosshair size using the current crosshairs menu :)

**Comment by Fohlen** [comment]
Does this really make sense if guislider can't handle it?

**Comment by Calinou** [comment]
I don't use the crosshair menu to adjust the size, so I never noticed it, sorry. Maybe we can change it into a text field like the mouse sensitivity?

**Comment by Fohlen** [comment]
Another way of doing it could be:

- bind the guislider to a temporary variable
- on focus leave set the mouse sensitivity to that temporary variable (which is an integer)
- more advanced users can then still use the command line to tweak things further

Does that sound probable?

**Comment by Calinou** [comment]
@Fohlen Sounds good to me :slightly_smiling_face:

**Comment by Fohlen** [comment]
If @SalatielSauer gives his go I will merge this. Best is to create a follow-up PR (or ticket) in the essential repository to make the necessary changes.

**Comment by SalatielSauer** [comment]
> Another way of doing it could be:
> 
> * bind the guislider to a temporary variable
> * on focus leave set the mouse sensitivity to that temporary variable (which is an integer)
> * more advanced users can then still use the command line to tweak things further
> 
> Does that sound probable?

@Fohlen you meant crosshairsize, right?
done here [9c52898](https://github.com/tomatenquark/essential/commit/9c52898849724f021d975fb978e9da99fb13988e), it should be ok to merge now

**Pull request merged**
