### PR TITLE
Add hidehudicons var

### LINKED ISSUE #62: Hide Health/Ammo HUD by default in Instagib
The HUD elements for health and ammo serve no practical purpose in Instagib gamemodes, and should be hidden by default for immersions sake. 

Health is absolutely useless, and it's not likely a player runs out of ammo in instagib. (Worth raising the question of whether ammo should just be infinite)

### PR DESCRIPTION
**Pull request by SalatielSauer**
- [x] my contribution will be licensed under [ZLIB](https://www.zlib.net/zlib_license.html) (for code)

This is my suggestion to close #62, similar to hidehud, but hides only the icons (keeping texts and crosshair)

image

### CODE REVIEW

**Comment by Calinou** [comment]
This should only apply to instagib modes.

**Comment by SalatielSauer** [comment]
> This should only apply to instagib modes.

Why limit it to instagib?
Players can choose whether to disable in all modes or just specific modes using cubescript...

**Comment by Calinou** [comment]
> Players can choose whether to disable in all modes or just specific modes using cubescript...

True, but I can't see any use cases for hiding your health, armor and ammo in modes where it actually matters :slightly_smiling_face:

**Comment by SalatielSauer** [comment]
I don't see the point in limiting it, it would be a few more characters in the code and less functionality...
we can make the command useful in other situations (when recording demos some people may want to keep their crosshair visible while hiding ammo icons :D)

**Comment by Delphik** [comment]
I really like this, nice job. Definitely feel like keeping the option available to all modes is the right call. I can see this being used for Race and other non-standard game-modes, as well as for short term effect in single-player.

**Pull request merged**
